# https://taskfile.dev

version: '3'

tasks:
  build_go_types:
    cmds:
      - |
        protoc account.proto campaign.proto common/error.proto common/nomenclatures.proto \
          -I/usr/include \
          --proto_path=protos \
          --go-grpc_opt=module=github.com/daritelska-platforma/types/go-types \
          --go_opt=module=github.com/daritelska-platforma/types/go-types \
          --go-grpc_out=go-types \
          --go_out=go-types
    silent: false
