name: Lint proto

on:
  workflow_dispatch:
  push: 
  pull_request:
    branches: [master]
    paths:
      - "protos/**"

jobs:
  run-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install protobuf
        run:
          sudo apt-get update && sudo apt-get -y install protobuf-compiler

      - name: Install task
        run:
          sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install Go proto tooling
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
          go get -u github.com/yoheimuta/protolint/cmd/protolint
          export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Lint protos
        working-directory: protos
        run: protolint lint .
